server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rafaelsulimann/ead-config-server-repo
          default-label: main
          username: rafaelsulimann
          password: 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

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost